# Generated by Django 5.2.3 on 2025-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('preferencias_raza', models.CharField(blank=True, max_length=100, null=True)),
                ('preferencias_edad', models.IntegerField(blank=True, null=True)),
                ('preferencias_tamaño', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
