# Generated by Django 5.2.3 on 2025-06-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_adopcion', '0003_raza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='temperamento',
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.CharField(default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='perro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[('chihuahua', 'Chihuahua'), ('labrador', 'Labrador'), ('caniche', 'Caniche')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perro',
            name='tamaño',
            field=models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perro',
            name='vacunado',
            field=models.BooleanField(default=False),
        ),
    ]
