# Generated by Django 5.2.3 on 2025-06-25 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_adopcion', '0004_remove_perro_temperamento_alter_perro_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_adopcion.raza'),
        ),
    ]
